name = "mato-reader"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "mato_reader_d1"
database_id = "<sẽ có sau khi tạo D1 trên Cloudflare>"

[[r2_buckets]]
binding = "MY_R2_BUCKET"
bucket_name = "mato-media"
preview_bucket_name = "mato-media"
